

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 